"""add email to coaches

Revision ID: 3c2f6474d743
Revises: 7736602d7292
Create Date: 2026-01-17 07:31:49.386351

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '3c2f6474d743'
down_revision = '7736602d7292'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('coaches', schema=None) as batch_op:
        batch_op.add_column(sa.Column('email', sa.Text(), nullable=True))
        batch_op.alter_column('password_hash',
               existing_type=sa.TEXT(),
               nullable=False)
        batch_op.create_unique_constraint(None, ['email'])

    with op.batch_alter_table('match_interests', schema=None) as batch_op:
        batch_op.drop_constraint(batch_op.f('match_interests_requesting_coach_id_fkey'), type_='foreignkey')
        batch_op.create_foreign_key(None, 'coaches', ['requesting_coach_id'], ['id'])

    with op.batch_alter_table('teams', schema=None) as batch_op:
        batch_op.drop_constraint(batch_op.f('teams_coach_id_fkey'), type_='foreignkey')
        batch_op.create_foreign_key(None, 'coaches', ['coach_id'], ['id'])

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('teams', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.create_foreign_key(batch_op.f('teams_coach_id_fkey'), 'coaches', ['coach_id'], ['id'], ondelete='CASCADE')

    with op.batch_alter_table('match_interests', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.create_foreign_key(batch_op.f('match_interests_requesting_coach_id_fkey'), 'coaches', ['requesting_coach_id'], ['id'], ondelete='CASCADE')

    with op.batch_alter_table('coaches', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='unique')
        batch_op.alter_column('password_hash',
               existing_type=sa.TEXT(),
               nullable=True)
        batch_op.drop_column('email')

    # ### end Alembic commands ###
