"""add teams table

Revision ID: 7736602d7292
Revises: cc8083077915
Create Date: 2026-01-17 04:19:48.150751

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = '7736602d7292'
down_revision = 'cc8083077915'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('coaches', schema=None) as batch_op:
        batch_op.add_column(sa.Column('password_hash', sa.Text(), nullable=True))
        batch_op.alter_column('user_id',
               existing_type=sa.UUID(),
               nullable=True)
        batch_op.create_unique_constraint(None, ['phone'])

    with op.batch_alter_table('messages', schema=None) as batch_op:
        batch_op.add_column(sa.Column('sender_id', sa.UUID(), nullable=False))
        batch_op.add_column(sa.Column('recipient_id', sa.UUID(), nullable=False))
        batch_op.add_column(sa.Column('content', sa.Text(), nullable=False))
        batch_op.add_column(sa.Column('is_read', sa.Boolean(), nullable=True))
        batch_op.drop_constraint(batch_op.f('messages_to_team_id_fkey'), type_='foreignkey')
        batch_op.drop_constraint(batch_op.f('messages_from_team_id_fkey'), type_='foreignkey')
        batch_op.create_foreign_key(None, 'coaches', ['recipient_id'], ['id'])
        batch_op.create_foreign_key(None, 'coaches', ['sender_id'], ['id'])
        batch_op.drop_column('status')
        batch_op.drop_column('from_team_id')
        batch_op.drop_column('proposed_date')
        batch_op.drop_column('to_team_id')
        batch_op.drop_column('venue')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('messages', schema=None) as batch_op:
        batch_op.add_column(sa.Column('venue', sa.VARCHAR(length=255), autoincrement=False, nullable=True))
        batch_op.add_column(sa.Column('to_team_id', sa.UUID(), autoincrement=False, nullable=False))
        batch_op.add_column(sa.Column('proposed_date', sa.DATE(), autoincrement=False, nullable=True))
        batch_op.add_column(sa.Column('from_team_id', sa.UUID(), autoincrement=False, nullable=False))
        batch_op.add_column(sa.Column('status', postgresql.ENUM('pending', 'accepted', 'declined', name='matchintereststatus'), autoincrement=False, nullable=False))
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.create_foreign_key(batch_op.f('messages_from_team_id_fkey'), 'teams', ['from_team_id'], ['id'])
        batch_op.create_foreign_key(batch_op.f('messages_to_team_id_fkey'), 'teams', ['to_team_id'], ['id'])
        batch_op.drop_column('is_read')
        batch_op.drop_column('content')
        batch_op.drop_column('recipient_id')
        batch_op.drop_column('sender_id')

    with op.batch_alter_table('coaches', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='unique')
        batch_op.alter_column('user_id',
               existing_type=sa.UUID(),
               nullable=False)
        batch_op.drop_column('password_hash')

    # ### end Alembic commands ###
