"""Added competition engine

Revision ID: c9e3aa20359f
Revises: e0b1f086b50d
Create Date: 2026-02-24 23:17:03.692324

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'c9e3aa20359f'
down_revision = 'e0b1f086b50d'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('competitions',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('season_id', sa.UUID(), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('stage_level', sa.String(length=50), nullable=False),
    sa.Column('region_id', sa.UUID(), nullable=True),
    sa.Column('county_id', sa.UUID(), nullable=True),
    sa.Column('format_type', sa.String(length=50), nullable=False),
    sa.Column('legs', sa.Integer(), nullable=False),
    sa.Column('points_win', sa.Integer(), nullable=True),
    sa.Column('points_draw', sa.Integer(), nullable=True),
    sa.Column('points_loss', sa.Integer(), nullable=True),
    sa.Column('status', sa.String(length=50), nullable=True),
    sa.Column('max_teams', sa.Integer(), nullable=True),
    sa.Column('min_teams', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['county_id'], ['counties.id'], ),
    sa.ForeignKeyConstraint(['region_id'], ['regions.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('season_id', 'name', name='uq_competition_season_name')
    )
    op.create_table('constituencies',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('county_id', sa.UUID(), nullable=False),
    sa.Column('name', sa.Text(), nullable=False),
    sa.Column('code', sa.String(length=20), nullable=True),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=True),
    sa.Column('updated_at', sa.DateTime(), server_default=sa.text('now()'), nullable=True),
    sa.ForeignKeyConstraint(['county_id'], ['counties.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('county_id', 'name', name='uq_constituency_county_name')
    )
    op.create_table('competition_advancement_rules',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('from_competition_id', sa.UUID(), nullable=False),
    sa.Column('to_competition_id', sa.UUID(), nullable=True),
    sa.Column('rule_type', sa.String(length=50), nullable=False),
    sa.Column('advancement_positions', sa.Integer(), nullable=True),
    sa.Column('auto_apply', sa.Boolean(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['from_competition_id'], ['competitions.id'], ),
    sa.ForeignKeyConstraint(['to_competition_id'], ['competitions.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('from_competition_id', 'rule_type', name='uq_advancement_rule_per_competition')
    )
    op.create_table('competition_groups',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('competition_id', sa.UUID(), nullable=False),
    sa.Column('name', sa.String(length=100), nullable=False),
    sa.Column('group_order', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['competition_id'], ['competitions.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('competition_id', 'name', name='uq_competition_group_name')
    )
    op.create_table('knockout_rounds',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('competition_id', sa.UUID(), nullable=False),
    sa.Column('round_name', sa.String(length=100), nullable=False),
    sa.Column('round_order', sa.Integer(), nullable=False),
    sa.Column('matches_per_pairing', sa.Integer(), nullable=True),
    sa.Column('status', sa.String(length=50), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['competition_id'], ['competitions.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('competition_id', 'round_order', name='uq_competition_round_order')
    )
    op.create_table('competition_teams',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('competition_id', sa.UUID(), nullable=False),
    sa.Column('team_id', sa.UUID(), nullable=False),
    sa.Column('manually_added', sa.Boolean(), nullable=True),
    sa.Column('seeded_position', sa.Integer(), nullable=True),
    sa.Column('group_id', sa.UUID(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['competition_id'], ['competitions.id'], ),
    sa.ForeignKeyConstraint(['group_id'], ['competition_groups.id'], ),
    sa.ForeignKeyConstraint(['team_id'], ['teams.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('competition_id', 'team_id', name='uq_competition_team')
    )
    with op.batch_alter_table('coaches', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_coaches_county_id'))
        batch_op.drop_constraint(batch_op.f('fk_coaches_county_id'), type_='foreignkey')
        batch_op.drop_column('email_verified')
        batch_op.drop_column('must_change_password')
        batch_op.drop_column('created_by_admin_id')
        batch_op.drop_column('county_id')

    with op.batch_alter_table('counties', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_counties_region_id'))

    with op.batch_alter_table('matches', schema=None) as batch_op:
        batch_op.add_column(sa.Column('competition_id', sa.UUID(), nullable=True))
        batch_op.add_column(sa.Column('group_id', sa.UUID(), nullable=True))
        batch_op.add_column(sa.Column('knockout_round_id', sa.UUID(), nullable=True))
        batch_op.create_foreign_key(None, 'competition_groups', ['group_id'], ['id'])
        batch_op.create_foreign_key(None, 'knockout_rounds', ['knockout_round_id'], ['id'])
        batch_op.create_foreign_key(None, 'competitions', ['competition_id'], ['id'])
        batch_op.drop_column('competition')

    with op.batch_alter_table('regions', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_regions_country_id'))

    with op.batch_alter_table('teams', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_teams_county_id'))
        batch_op.drop_constraint(batch_op.f('fk_teams_county_id'), type_='foreignkey')
        batch_op.drop_column('created_by_admin_id')
        batch_op.drop_column('county_id')

    with op.batch_alter_table('wards', schema=None) as batch_op:
        batch_op.add_column(sa.Column('constituency_id', sa.UUID(), nullable=True))
        batch_op.drop_index(batch_op.f('ix_wards_county_id'))
        batch_op.drop_constraint(batch_op.f('uq_ward_county_name'), type_='unique')
        batch_op.create_unique_constraint('uq_ward_constituency_name', ['constituency_id', 'name'])
        batch_op.create_foreign_key(None, 'constituencies', ['constituency_id'], ['id'])

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('wards', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.drop_constraint('uq_ward_constituency_name', type_='unique')
        batch_op.create_unique_constraint(batch_op.f('uq_ward_county_name'), ['county_id', 'name'], postgresql_nulls_not_distinct=False)
        batch_op.create_index(batch_op.f('ix_wards_county_id'), ['county_id'], unique=False)
        batch_op.drop_column('constituency_id')

    with op.batch_alter_table('teams', schema=None) as batch_op:
        batch_op.add_column(sa.Column('county_id', sa.UUID(), autoincrement=False, nullable=True))
        batch_op.add_column(sa.Column('created_by_admin_id', sa.UUID(), autoincrement=False, nullable=True))
        batch_op.create_foreign_key(batch_op.f('fk_teams_county_id'), 'counties', ['county_id'], ['id'])
        batch_op.create_index(batch_op.f('ix_teams_county_id'), ['county_id'], unique=False)

    with op.batch_alter_table('regions', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_regions_country_id'), ['country_id'], unique=False)

    with op.batch_alter_table('matches', schema=None) as batch_op:
        batch_op.add_column(sa.Column('competition', sa.TEXT(), autoincrement=False, nullable=True))
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.drop_column('knockout_round_id')
        batch_op.drop_column('group_id')
        batch_op.drop_column('competition_id')

    with op.batch_alter_table('counties', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_counties_region_id'), ['region_id'], unique=False)

    with op.batch_alter_table('coaches', schema=None) as batch_op:
        batch_op.add_column(sa.Column('county_id', sa.UUID(), autoincrement=False, nullable=True))
        batch_op.add_column(sa.Column('created_by_admin_id', sa.UUID(), autoincrement=False, nullable=True))
        batch_op.add_column(sa.Column('must_change_password', sa.BOOLEAN(), server_default=sa.text('false'), autoincrement=False, nullable=False))
        batch_op.add_column(sa.Column('email_verified', sa.BOOLEAN(), server_default=sa.text('false'), autoincrement=False, nullable=False))
        batch_op.create_foreign_key(batch_op.f('fk_coaches_county_id'), 'counties', ['county_id'], ['id'])
        batch_op.create_index(batch_op.f('ix_coaches_county_id'), ['county_id'], unique=False)

    op.drop_table('competition_teams')
    op.drop_table('knockout_rounds')
    op.drop_table('competition_groups')
    op.drop_table('competition_advancement_rules')
    op.drop_table('constituencies')
    op.drop_table('competitions')
    # ### end Alembic commands ###
